project_id = "hnxnvdzrwbtmcohdptfq"

[functions.voice-to-text]
verify_jwt = false

[functions.avatar-file-compress]
verify_jwt = true

[functions.web-scraper]
verify_jwt = true

[functions.personalized-ai-response]
verify_jwt = false

[functions.personalized-ai-training]
verify_jwt = true

[functions.voice-cloning]
verify_jwt = true

[functions.voice-chat-stream]
verify_jwt = false

[functions.razorpay-create-order]
verify_jwt = true

[functions.razorpay-verify-payment]
verify_jwt = true
